baseurl = "https://chinese.githuka.com/"
title = " 楚大洋"
author = "Wilfred Githuka"
paginate = 6
theme = "arabica"

[params]
    description = "Life Long Chinese Learner"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "twitter.com/wilfredgithuka"
    facebook = "none"
