baseURL = "https://chinese.githuka.com"
title = "Wilfred Githuka"
themesDir = "/home/wilfred/ssc/themes/"
theme = "hugo-theme-m10c"
paginate = 10

[params]
  author = "Wilfred Githuka"
  description = "Lifelong Chinese Learner"
  [[params.social]]
    name = "github"
    url = "https://github.com/wilfredgithuka"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/wilfredgithuka"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
